// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StructProject.Database.Context;

#nullable disable

namespace StructProject.Database.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260705155956_PersistenceS7")]
    partial class PersistenceS7
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("StructProject.Database.Entities.PlayerDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score");

                    b.HasKey("Id");

                    b.ToTable("players");
                });

            modelBuilder.Entity("StructProject.Database.Entities.PlayerProfileDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("BestScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("best_score");

                    b.Property<int>("BestWave")
                        .HasColumnType("INTEGER")
                        .HasColumnName("best_wave");

                    b.Property<int>("Coins")
                        .HasColumnType("INTEGER")
                        .HasColumnName("coins");

                    b.Property<int>("DamageLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("damage_level");

                    b.Property<int>("ExtraMaxHp")
                        .HasColumnType("INTEGER")
                        .HasColumnName("extra_max_hp");

                    b.Property<DateTime>("LastPlayedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_played_at");

                    b.Property<int>("SpeedLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("speed_level");

                    b.HasKey("Id");

                    b.ToTable("players_x");
                });

            modelBuilder.Entity("StructProject.Database.Entities.SaveSlotDB", b =>
                {
                    b.Property<int>("Slot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("slot");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("JsonState")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("json_state");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Slot");

                    b.ToTable("save_slots");
                });

            modelBuilder.Entity("StructProject.Database.Entities.ScoreEntryDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score");

                    b.Property<int>("Wave")
                        .HasColumnType("INTEGER")
                        .HasColumnName("wave");

                    b.HasKey("Id");

                    b.ToTable("score_entries_x");
                });
#pragma warning restore 612, 618
        }
    }
}
